<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="EPMXGUAW0354" name="com.testautomation.TestRunner.TestRunner" tests="2" failures="1" timestamp="2019-10-25T23:30:15 CDT" time="24.460" errors="0">
  <testcase name="feature" time="12.127" classname="com.testautomation.TestRunner.TestRunner">
    <failure type="java.lang.AssertionError" message="No se pudo completar la validacionjava.lang.AssertionError: did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: No se pudo completar la validacionjava.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at com.testautomation.StepDefinitions.LoginGalenFramework.i_validate_the_another_note(LoginGalenFramework.java:140)
at âœ½.I validate the another note "Segundo Mensaje"(./features/GalenPageTesting.feature:21)
]]>
    </failure>
  </testcase> <!-- feature -->
  <testcase name="feature" time="12.333" classname="com.testautomation.TestRunner.TestRunner"/>
</testsuite> <!-- com.testautomation.TestRunner.TestRunner -->
