<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="EPMXGUAW0506" name="com.testautomation.TestRunner.TestRunner" tests="5" failures="2" timestamp="2019-11-07T10:43:07 CST" time="165.423" errors="0">
  <testcase name="feature" time="21.137" classname="com.testautomation.TestRunner.TestRunner"/>
  <testcase name="feature" time="50.776" classname="com.testautomation.TestRunner.TestRunner">
    <failure type="java.lang.AssertionError" message="PRUEBA FALLO ASSERT TESTNG">
      <![CDATA[java.lang.AssertionError: PRUEBA FALLO ASSERT TESTNG
at org.testng.Assert.fail(Assert.java:97)
at com.testautomation.Listeners.ExtentReportListener.testStepHandle(ExtentReportListener.java:55)
at com.testautomation.StepDefinitions.LoginGalenFramework.i_validate_the_another_note(LoginGalenFramework.java:109)
at ✽.I validate the another note "Segundo Mensaje"(./features/GalenPageTesting.feature:47)
]]>
    </failure>
  </testcase> <!-- feature -->
  <testcase name="feature" time="50.939" classname="com.testautomation.TestRunner.TestRunner">
    <failure type="java.lang.AssertionError" message="PRUEBA FALLO ASSERT TESTNG">
      <![CDATA[java.lang.AssertionError: PRUEBA FALLO ASSERT TESTNG
at org.testng.Assert.fail(Assert.java:97)
at com.testautomation.Listeners.ExtentReportListener.testStepHandle(ExtentReportListener.java:55)
at com.testautomation.StepDefinitions.LoginGalenFramework.i_validate_the_another_note(LoginGalenFramework.java:109)
at ✽.I validate the another note "Segundo Mensaje"(./features/GalenPageTesting.feature:38)
]]>
    </failure>
  </testcase> <!-- feature -->
  <testcase name="feature" time="21.357" classname="com.testautomation.TestRunner.TestRunner"/>
  <testcase name="feature" time="21.214" classname="com.testautomation.TestRunner.TestRunner"/>
</testsuite> <!-- com.testautomation.TestRunner.TestRunner -->
